# keras conversion code

SNN 모델을 저장하되, IF 레이어는 ReLU로 바꿔서 저장하도록 한다. 대신 IF 레이어의 설정값은 따로 찍어서 보내기.

In [1]:
# path = '/data/hongwonseok/ECG-SNN/KIST/MLP/MLP_binary_NO_BatchNorm.pth'

path = '/home/hschoi/data/leehyunwon/ECG-SNN/SNN_MLP_ver5_poisson_binary_encoders187_hidden1000_encoderGradTrue_early30_lr0.001_threshold1.0_2024_09_12_05_09_45.pt'
 
 

In [2]:
import torch

model = torch.load(path)
model

/tmp/ipykernel_934652/3090495766.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(path)


{'epoch': 66,
 'model_state_dict': OrderedDict([('hidden.0.weight',
               tensor([[ 0.0231,  0.0119, -0.0370,  ..., -0.2979, -0.2210, -0.2029],
                       [ 0.1685,  0.0485, -0.0253,  ...,  0.2048,  0.1987,  0.2106],
                       [ 0.1356, -0.1939,  0.3692,  ..., -0.0627, -0.1177,  0.1197],
                       ...,
                       [-0.1195, -0.1124,  0.0281,  ..., -0.1612, -0.3343, -0.3164],
                       [ 0.0059, -0.0585, -0.0193,  ..., -0.1536, -0.1007, -0.1129],
                       [-0.2445, -0.2495, -0.0261,  ..., -0.1434, -0.2190, -0.2391]],
                      device='cuda:0')),
              ('hidden2.0.weight',
               tensor([[-0.2143,  0.1613,  0.0040,  ..., -0.0696, -0.0372, -0.0293],
                       [-0.0996, -0.0811,  0.1295,  ..., -0.2103, -0.0992, -0.2512],
                       [-0.0976, -0.0391, -0.0138,  ...,  0.0792, -0.0135,  0.2290],
                       ...,
                       [ 0.0669,  

In [3]:
weight = model['model_state_dict']
weight

OrderedDict([('hidden.0.weight',
              tensor([[ 0.0231,  0.0119, -0.0370,  ..., -0.2979, -0.2210, -0.2029],
                      [ 0.1685,  0.0485, -0.0253,  ...,  0.2048,  0.1987,  0.2106],
                      [ 0.1356, -0.1939,  0.3692,  ..., -0.0627, -0.1177,  0.1197],
                      ...,
                      [-0.1195, -0.1124,  0.0281,  ..., -0.1612, -0.3343, -0.3164],
                      [ 0.0059, -0.0585, -0.0193,  ..., -0.1536, -0.1007, -0.1129],
                      [-0.2445, -0.2495, -0.0261,  ..., -0.1434, -0.2190, -0.2391]],
                     device='cuda:0')),
             ('hidden2.0.weight',
              tensor([[-0.2143,  0.1613,  0.0040,  ..., -0.0696, -0.0372, -0.0293],
                      [-0.0996, -0.0811,  0.1295,  ..., -0.2103, -0.0992, -0.2512],
                      [-0.0976, -0.0391, -0.0138,  ...,  0.0792, -0.0135,  0.2290],
                      ...,
                      [ 0.0669,  0.1280, -0.2703,  ..., -0.1944,  0.0026,  0.0127]

In [4]:
weight.items()

odict_items([('hidden.0.weight', tensor([[ 0.0231,  0.0119, -0.0370,  ..., -0.2979, -0.2210, -0.2029],
        [ 0.1685,  0.0485, -0.0253,  ...,  0.2048,  0.1987,  0.2106],
        [ 0.1356, -0.1939,  0.3692,  ..., -0.0627, -0.1177,  0.1197],
        ...,
        [-0.1195, -0.1124,  0.0281,  ..., -0.1612, -0.3343, -0.3164],
        [ 0.0059, -0.0585, -0.0193,  ..., -0.1536, -0.1007, -0.1129],
        [-0.2445, -0.2495, -0.0261,  ..., -0.1434, -0.2190, -0.2391]],
       device='cuda:0')), ('hidden2.0.weight', tensor([[-0.2143,  0.1613,  0.0040,  ..., -0.0696, -0.0372, -0.0293],
        [-0.0996, -0.0811,  0.1295,  ..., -0.2103, -0.0992, -0.2512],
        [-0.0976, -0.0391, -0.0138,  ...,  0.0792, -0.0135,  0.2290],
        ...,
        [ 0.0669,  0.1280, -0.2703,  ..., -0.1944,  0.0026,  0.0127],
        [-0.3390, -0.0237, -0.1034,  ...,  0.0072, -0.0205, -0.0101],
        [-0.0139,  0.1176,  0.1325,  ..., -0.0490,  0.0007,  0.0116]],
       device='cuda:0')), ('layer.0.weight', tensor(

In [5]:
import torch
import torch.nn as nn
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, ReLU, Dropout, InputLayer
from tensorflow.keras.layers import ZeroPadding1D, Conv1D, BatchNormalization, ReLU, AveragePooling1D, Flatten, Dense

2024-09-12 13:23:20.747228: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-12 13:23:20.751763: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-12 13:23:20.764500: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-12 13:23:20.785956: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-12 13:23:20.791912: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attemptin

일단 GPT에게 변환 코드 예시를 받아놨으니 그걸로 진행해보자.

**KIST용으로 바꿀 땐 hidden layer 뉴런 수가 1000개 임에 주의!!!!**

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, ReLU

def create_keras_model_SNN(num_classes, num_encoders, hidden_size, hidden_size_2):
    # 입력 레이어 정의
    inputs = Input(shape=(num_encoders,), name='input')
    
    # 첫 번째 히든 레이어
    x = Dense(hidden_size, use_bias=False, name='hidden1')(inputs)
    x = ReLU(name='relu1')(x)
    
    # 두 번째 히든 레이어
    x = Dense(hidden_size_2, use_bias=False, name='hidden2')(x)
    x = ReLU(name='relu2')(x)
    
    # 출력 레이어
    predictions = Dense(num_classes, use_bias=False, name='output')(x)
    predictions = ReLU(name='output_relu')(predictions)  # IFNode를 ReLU로 치환

    # 모델 생성
    model = Model(inputs=inputs, outputs=predictions)
    
    return model

# 모델 생성 예시
keras_model = create_keras_model_SNN(num_classes=2, num_encoders=187, hidden_size=1000, hidden_size_2=1000)

# 모델 구조 확인
keras_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input (InputLayer)              │ (None, 187)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden1 (Dense)                 │ (None, 1000)           │       187,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu1 (ReLU)                    │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden2 (Dense)                 │ (None, 1000)           │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu2 (ReLU)                    │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 2)              │         2,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_relu (ReLU)              │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,189,000 (4.54 MB)

 Trainable params: 1,189,000 (4.54 MB)

 Non-trainable params: 0 (0.00 B)

In [9]:
# keras 모델의 초기 가중치 확인
for layer in keras_model.layers:
    weights = layer.get_weights()
    print(f"Layer: {layer.name}")
    for temp_weight in weights:
        print(temp_weight)

Layer: input
Layer: hidden1
[[ 0.0103347   0.05068844 -0.06189962 ... -0.04612438 -0.0644438
   0.03493562]
 [-0.04433578 -0.05693173 -0.01969697 ... -0.04005923  0.06866184
   0.00738701]
 [-0.05696339 -0.01744635 -0.01025654 ... -0.02179777 -0.02748502
   0.01735427]
 ...
 [-0.06663925 -0.05753145  0.0624495  ...  0.06952663 -0.00921234
   0.0312437 ]
 [ 0.04054857  0.00584842  0.04294197 ... -0.0551069  -0.01249029
  -0.0577582 ]
 [-0.05536159  0.06312518  0.01701386 ... -0.03947213 -0.01049097
  -0.04536577]]
Layer: relu1
Layer: hidden2
[[ 0.01954382  0.02189889  0.04611427 ... -0.01125864  0.03846181
  -0.00662447]
 [ 0.03167409 -0.03980071 -0.01605011 ...  0.03196427  0.03466277
  -0.03194277]
 [-0.03750982  0.01401582 -0.03510468 ...  0.04383923 -0.04001586
  -0.02558376]
 ...
 [ 0.03669073 -0.01300453 -0.01461833 ... -0.00408691  0.01004397
  -0.0544884 ]
 [ 0.03594805  0.00754733 -0.05413356 ... -0.04999237 -0.02942714
   0.00872013]
 [ 0.01409571  0.04311765 -0.04740681 ... -

가중치 추출하고 케라스 모델에 대입하기

왜인진 모르겠지만 cuda 커널 이미지가 안맞는다 하다가 또 된다고 하다가 그런다. 일단 시도해서 될 때 계속 진행하도록 한다.

In [13]:
import torch
print(torch.__version__)  # PyTorch 버전 확인
print(torch.version.cuda)  # CUDA 버전 확인
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

!export CUDA_LAUNCH_BLOCKING=1

# PyTorch에서 가중치 추출 및 Keras에 적용
pt_weights = {k: v.cpu().numpy() for k, v in weight.items()}

# Keras 가중치 설정
# pytorch의 모델 가중치는 (출력, 입력) 순서로 저장되고 케라스는 그 반대이므로 Transpose 필요
keras_model.get_layer('hidden1').set_weights([pt_weights['hidden.0.weight'].T]) # bias 빼기!
keras_model.get_layer('hidden2').set_weights([pt_weights['hidden2.0.weight'].T])
keras_model.get_layer('output').set_weights([pt_weights['layer.0.weight'].T])

# 잘 들어갔나 확인?
keras_model.summary()

2.4.0
11.8
True


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input (InputLayer)              │ (None, 187)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden1 (Dense)                 │ (None, 1000)           │       187,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu1 (ReLU)                    │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden2 (Dense)                 │ (None, 1000)           │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu2 (ReLU)                    │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 2)              │         2,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_relu (ReLU)              │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,189,000 (4.54 MB)

 Trainable params: 1,189,000 (4.54 MB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# 모델 저장
keras_model.save('poisson_1000_converted_model.h5')

In [15]:
# 모델의 가중치 확인
for layer in keras_model.layers:
    weights = layer.get_weights()
    print(f"Layer: {layer.name}")
    for temp_weight in weights:
        print(temp_weight)

Layer: input
Layer: hidden1
[[ 0.02307094  0.16853595  0.1356288  ... -0.11953812  0.00585862
  -0.24453036]
 [ 0.01194622  0.04850474 -0.19393311 ... -0.11237578 -0.05853188
  -0.24945214]
 [-0.0369759  -0.02532746  0.36918268 ...  0.02813624 -0.0193215
  -0.02611096]
 ...
 [-0.2978546   0.20477739 -0.06271742 ... -0.16116704 -0.15358803
  -0.14336602]
 [-0.22104879  0.1987174  -0.11765699 ... -0.3342545  -0.10068992
  -0.21899201]
 [-0.2028826   0.21055873  0.11968018 ... -0.31641975 -0.11287399
  -0.2390547 ]]
Layer: relu1
Layer: hidden2
[[-0.21434933 -0.09958602 -0.09763815 ...  0.06691882 -0.33902758
  -0.01391515]
 [ 0.16128036 -0.0811445  -0.03911572 ...  0.12797529 -0.02365707
   0.11760265]
 [ 0.00403396  0.12954617 -0.01377724 ... -0.2703215  -0.10340067
   0.13247395]
 ...
 [-0.06958194 -0.2103122   0.07921408 ... -0.19442059  0.00717742
  -0.0489803 ]
 [-0.03720324 -0.09917426 -0.0134587  ...  0.0026057  -0.02053288
   0.00066729]
 [-0.02934875 -0.25123113  0.22900324 ...  

In [16]:
from tensorflow.keras.models import load_model

# 저장된 모델 로드
loaded_model = load_model('/home/hschoi/leehyunwon/ECG-SNN/to_keras_conversion/poisson_1000_converted_model.h5')


In [17]:
loaded_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input (InputLayer)              │ (None, 187)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden1 (Dense)                 │ (None, 1000)           │       187,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu1 (ReLU)                    │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden2 (Dense)                 │ (None, 1000)           │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu2 (ReLU)                    │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 2)              │         2,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_relu (ReLU)              │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,189,000 (4.54 MB)

 Trainable params: 1,189,000 (4.54 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# 로드된 모델의 가중치 확인
for layer in loaded_model.layers:
    weights = layer.get_weights()
    print(f"Layer: {layer.name}")
    for temp_weight in weights:
        print(temp_weight)


Layer: input
Layer: hidden1
[[ 0.02307094  0.16853595  0.1356288  ... -0.11953812  0.00585862
  -0.24453036]
 [ 0.01194622  0.04850474 -0.19393311 ... -0.11237578 -0.05853188
  -0.24945214]
 [-0.0369759  -0.02532746  0.36918268 ...  0.02813624 -0.0193215
  -0.02611096]
 ...
 [-0.2978546   0.20477739 -0.06271742 ... -0.16116704 -0.15358803
  -0.14336602]
 [-0.22104879  0.1987174  -0.11765699 ... -0.3342545  -0.10068992
  -0.21899201]
 [-0.2028826   0.21055873  0.11968018 ... -0.31641975 -0.11287399
  -0.2390547 ]]
Layer: relu1
Layer: hidden2
[[-0.21434933 -0.09958602 -0.09763815 ...  0.06691882 -0.33902758
  -0.01391515]
 [ 0.16128036 -0.0811445  -0.03911572 ...  0.12797529 -0.02365707
   0.11760265]
 [ 0.00403396  0.12954617 -0.01377724 ... -0.2703215  -0.10340067
   0.13247395]
 ...
 [-0.06958194 -0.2103122   0.07921408 ... -0.19442059  0.00717742
  -0.0489803 ]
 [-0.03720324 -0.09917426 -0.0134587  ...  0.0026057  -0.02053288
   0.00066729]
 [-0.02934875 -0.25123113  0.22900324 ...  