# keras conversion code

SNN 모델을 저장하되, IF 레이어는 ReLU로 바꿔서 저장하도록 한다. 대신 IF 레이어의 설정값은 따로 찍어서 보내기.
pth_to_h5_my_version의 filter CNN 버전, 인코더가 내부에 들어가있으므로 그 이후의 모델 가중치를 따로 저장할 수 있도록 한다.

**주의점 : keras version 2.11이 들어간 환경에서 실행할 것! (KIST의 Neu+ 칩 구동환경과 일치시켜야 함)**

In [5]:
# path = '/data/hongwonseok/ECG-SNN/KIST/MLP/MLP_binary_NO_BatchNorm.pth'

path = '/home/hschoi/data/leehyunwon/ECG-SNN/SNN_MLP_ver5_filter_CNN_LIF_3layer_binary_channel1000_hidden1000_encoderGradTrue_early25_lr0.001_threshold1.0_2024_10_29_11_14_10_lastEpoch.pt'
 
 

In [6]:
import torch

model = torch.load(path)
model

/tmp/ipykernel_2240752/3090495766.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(path)


{'epoch': 299,
 'model_state_dict': OrderedDict([('cnn_encoders.weight',
               tensor([[[-2.5867e+00, -1.7425e+00, -2.1379e+00,  ...,  4.1450e-01,
                          4.4089e-01,  1.7568e-01]],
               
                       [[ 1.0223e+00,  4.3495e-01,  4.0459e-01,  ..., -1.0061e-01,
                         -1.5723e-02,  6.2172e-01]],
               
                       [[-1.5526e+01, -1.5310e+01, -1.4806e+01,  ..., -2.3676e+00,
                         -2.0556e+00, -1.7144e+00]],
               
                       ...,
               
                       [[-4.3718e+01, -4.3636e+01, -4.3035e+01,  ..., -7.2167e+00,
                         -6.0965e+00, -4.8562e+00]],
               
                       [[-9.5984e+00, -9.7534e+00, -9.2370e+00,  ..., -1.2113e+00,
                         -8.3315e-01, -9.0879e-01]],
               
                       [[-1.6128e+01, -1.6487e+01, -1.5631e+01,  ..., -2.4720e+00,
                         -2.2128e+00, -1

In [11]:
weight = model['model_state_dict']
weight

OrderedDict([('cnn_encoders.weight',
              tensor([[[-2.5867e+00, -1.7425e+00, -2.1379e+00,  ...,  4.1450e-01,
                         4.4089e-01,  1.7568e-01]],
              
                      [[ 1.0223e+00,  4.3495e-01,  4.0459e-01,  ..., -1.0061e-01,
                        -1.5723e-02,  6.2172e-01]],
              
                      [[-1.5526e+01, -1.5310e+01, -1.4806e+01,  ..., -2.3676e+00,
                        -2.0556e+00, -1.7144e+00]],
              
                      ...,
              
                      [[-4.3718e+01, -4.3636e+01, -4.3035e+01,  ..., -7.2167e+00,
                        -6.0965e+00, -4.8562e+00]],
              
                      [[-9.5984e+00, -9.7534e+00, -9.2370e+00,  ..., -1.2113e+00,
                        -8.3315e-01, -9.0879e-01]],
              
                      [[-1.6128e+01, -1.6487e+01, -1.5631e+01,  ..., -2.4720e+00,
                        -2.2128e+00, -1.8026e+00]]], device='cuda:0')),
             ('hidden.

In [12]:
weight.items()

odict_items([('cnn_encoders.weight', tensor([[[-2.5867e+00, -1.7425e+00, -2.1379e+00,  ...,  4.1450e-01,
           4.4089e-01,  1.7568e-01]],

        [[ 1.0223e+00,  4.3495e-01,  4.0459e-01,  ..., -1.0061e-01,
          -1.5723e-02,  6.2172e-01]],

        [[-1.5526e+01, -1.5310e+01, -1.4806e+01,  ..., -2.3676e+00,
          -2.0556e+00, -1.7144e+00]],

        ...,

        [[-4.3718e+01, -4.3636e+01, -4.3035e+01,  ..., -7.2167e+00,
          -6.0965e+00, -4.8562e+00]],

        [[-9.5984e+00, -9.7534e+00, -9.2370e+00,  ..., -1.2113e+00,
          -8.3315e-01, -9.0879e-01]],

        [[-1.6128e+01, -1.6487e+01, -1.5631e+01,  ..., -2.4720e+00,
          -2.2128e+00, -1.8026e+00]]], device='cuda:0')), ('hidden.0.weight', tensor([[-7.7588e-01,  5.7307e-01, -5.4228e-03,  ..., -8.7680e-03,
          2.3885e-01, -2.2579e-03],
        [-1.1902e+00, -5.2867e+00, -5.3639e+00,  ...,  1.9194e-02,
         -7.0197e-01, -9.7548e-01],
        [ 1.0580e-02, -4.9229e-01, -3.9028e-02,  ...,  1.4601e

### shape 확인
filter CNN의 hidden 레이어가 어떻게 생겨먹었는지 알 필요가 있을 것이다. 첫 hidden 레이어의 입력 크기를 그에 맞춰야 하기 때문.

In [23]:
temp_weights = {k: v.cpu().numpy() for k, v in weight.items()}
temp_weights['hidden.0.weight'].shape

(1000, 1000)

In [24]:
import torch
import torch.nn as nn
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, ReLU, Dropout, InputLayer
from tensorflow.keras.layers import ZeroPadding1D, Conv1D, BatchNormalization, ReLU, AveragePooling1D, Flatten, Dense

일단 GPT에게 변환 코드 예시를 받아놨으니 그걸로 진행해보자.

**KIST용으로 바꿀 땐 hidden layer 뉴런 수가 1000개 임에 주의!!!!**

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, ReLU

def create_keras_model_SNN(num_classes, num_encoders, hidden_size, hidden_size_2):
    # 입력 레이어 정의
    inputs = Input(shape=(num_encoders,), name='input')
    
    # 첫 번째 히든 레이어
    x = Dense(hidden_size, use_bias=False, name='hidden1')(inputs)
    x = ReLU(name='relu1')(x)
    
    # 히든레이어 하나만 써서 학습하는 모델로 변경
    # # 두 번째 히든 레이어
    # x = Dense(hidden_size_2, use_bias=False, name='hidden2')(x)
    # x = ReLU(name='relu2')(x)
    
    # 출력 레이어
    predictions = Dense(num_classes, use_bias=False, name='output')(x)
    predictions = ReLU(name='output_relu')(predictions)  # IFNode를 ReLU로 치환

    # 모델 생성
    model = Model(inputs=inputs, outputs=predictions)
    
    return model

# 모델 생성 예시
keras_model = create_keras_model_SNN(num_classes=2, num_encoders=1000, hidden_size=1000, hidden_size_2=1000) # 필터 인코더 제외한 hidden의 시작 부분도 1000이다.

# 모델 구조 확인
keras_model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 1000)]            0         
                                                                 
 hidden1 (Dense)             (None, 1000)              1000000   
                                                                 
 relu1 (ReLU)                (None, 1000)              0         
                                                                 
 output (Dense)              (None, 2)                 2000      
                                                                 
 output_relu (ReLU)          (None, 2)                 0         
                                                                 
Total params: 1,002,000
Trainable params: 1,002,000
Non-trainable params: 0
_________________________________________________________________


In [26]:
# keras 모델의 초기 가중치 확인
for layer in keras_model.layers:
    weights = layer.get_weights()
    print(f"Layer: {layer.name}")
    for temp_weight in weights:
        print(temp_weight)

Layer: input
Layer: hidden1
[[-0.05057826 -0.05207479  0.05153325 ... -0.05238639 -0.01452087
  -0.00053141]
 [-0.02624729 -0.00825414 -0.03428898 ...  0.00789499  0.00030709
  -0.00209925]
 [ 0.02744946 -0.00081627 -0.0542388  ...  0.02679453  0.04299771
  -0.03263053]
 ...
 [ 0.00168516  0.02037694  0.04997388 ... -0.04673339 -0.03101406
  -0.01109533]
 [ 0.02157476 -0.03751058  0.03493372 ...  0.03758385  0.00080955
   0.04368544]
 [ 0.04831579 -0.05065305 -0.05235521 ...  0.0129432  -0.03955241
   0.02133524]]
Layer: relu1
Layer: output
[[ 0.07435356 -0.04402163]
 [ 0.02818016  0.00764083]
 [ 0.03053914 -0.03700504]
 ...
 [-0.06837261 -0.0223956 ]
 [-0.06721395 -0.00777108]
 [-0.06685384  0.02789634]]
Layer: output_relu


가중치 추출하고 케라스 모델에 대입하기

왜인진 모르겠지만 cuda 커널 이미지가 안맞는다 하다가 또 된다고 하다가 그런다. 일단 시도해서 될 때 계속 진행하도록 한다.

In [27]:
import torch
print(torch.__version__)  # PyTorch 버전 확인
print(torch.version.cuda)  # CUDA 버전 확인
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

!export CUDA_LAUNCH_BLOCKING=1

# PyTorch에서 가중치 추출 및 Keras에 적용
pt_weights = {k: v.cpu().numpy() for k, v in weight.items()}

# Keras 가중치 설정
# pytorch의 모델 가중치는 (출력, 입력) 순서로 저장되고 케라스는 그 반대이므로 Transpose 필요
keras_model.get_layer('hidden1').set_weights([pt_weights['hidden.0.weight'].T]) # bias 빼기!
# keras_model.get_layer('hidden2').set_weights([pt_weights['hidden2.0.weight'].T]) # 레이어 1개만 사용하는 경우 빼야 함!
keras_model.get_layer('output').set_weights([pt_weights['layer.0.weight'].T])

# 잘 들어갔나 확인?
keras_model.summary()

2.4.1
11.8
True
Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 1000)]            0         
                                                                 
 hidden1 (Dense)             (None, 1000)              1000000   
                                                                 
 relu1 (ReLU)                (None, 1000)              0         
                                                                 
 output (Dense)              (None, 2)                 2000      
                                                                 
 output_relu (ReLU)          (None, 2)                 0         
                                                                 
Total params: 1,002,000
Trainable params: 1,002,000
Non-trainable params: 0
_________________________________________________________________


In [30]:
# 모델 저장
keras_model.save('filterCNN_1000_LIF.h5')

In [31]:
# 모델의 가중치 확인
for layer in keras_model.layers:
    weights = layer.get_weights()
    print(f"Layer: {layer.name}")
    for temp_weight in weights:
        print(temp_weight)

Layer: input
Layer: hidden1
[[-7.75878429e-01 -1.19023597e+00  1.05803665e-02 ... -1.87419534e-01
  -8.81674588e-02 -1.13365781e+00]
 [ 5.73069751e-01 -5.28673029e+00 -4.92291212e-01 ...  5.65622747e-01
   1.00063050e+00 -4.94418430e+00]
 [-5.42276213e-03 -5.36391163e+00 -3.90276350e-02 ... -2.11385891e-01
   7.09488168e-02 -4.94481707e+00]
 ...
 [-8.76797549e-03  1.91937704e-02  1.46009056e-02 ...  2.60544308e-02
  -1.54353362e-02 -4.95032873e-03]
 [ 2.38846213e-01 -7.01967180e-01  2.46308967e-02 ... -2.23279506e-01
   1.73493788e-01 -6.58773601e-01]
 [-2.25789729e-03 -9.75476086e-01  5.75257778e-01 ...  6.82233632e-01
  -2.14508677e+00 -9.96322691e-01]]
Layer: relu1
Layer: output
[[ 0.49932745 -0.49440542]
 [-0.03003345 -0.00601534]
 [ 0.531287   -0.3779337 ]
 ...
 [ 0.36814916 -0.4443905 ]
 [ 0.28471193 -0.43030402]
 [-0.02311547 -0.01046609]]
Layer: output_relu


In [32]:
from tensorflow.keras.models import load_model

# 저장된 모델 로드
loaded_model = load_model('/home/hschoi/leehyunwon/ECG-SNN/to_keras_conversion/filterCNN_1000_LIF.h5')


In [33]:
loaded_model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 1000)]            0         
                                                                 
 hidden1 (Dense)             (None, 1000)              1000000   
                                                                 
 relu1 (ReLU)                (None, 1000)              0         
                                                                 
 output (Dense)              (None, 2)                 2000      
                                                                 
 output_relu (ReLU)          (None, 2)                 0         
                                                                 
Total params: 1,002,000
Trainable params: 1,002,000
Non-trainable params: 0
_________________________________________________________________


In [34]:
# 로드된 모델의 가중치 확인
for layer in loaded_model.layers:
    weights = layer.get_weights()
    print(f"Layer: {layer.name}")
    for temp_weight in weights:
        print(temp_weight)


Layer: input
Layer: hidden1
[[-7.75878429e-01 -1.19023597e+00  1.05803665e-02 ... -1.87419534e-01
  -8.81674588e-02 -1.13365781e+00]
 [ 5.73069751e-01 -5.28673029e+00 -4.92291212e-01 ...  5.65622747e-01
   1.00063050e+00 -4.94418430e+00]
 [-5.42276213e-03 -5.36391163e+00 -3.90276350e-02 ... -2.11385891e-01
   7.09488168e-02 -4.94481707e+00]
 ...
 [-8.76797549e-03  1.91937704e-02  1.46009056e-02 ...  2.60544308e-02
  -1.54353362e-02 -4.95032873e-03]
 [ 2.38846213e-01 -7.01967180e-01  2.46308967e-02 ... -2.23279506e-01
   1.73493788e-01 -6.58773601e-01]
 [-2.25789729e-03 -9.75476086e-01  5.75257778e-01 ...  6.82233632e-01
  -2.14508677e+00 -9.96322691e-01]]
Layer: relu1
Layer: output
[[ 0.49932745 -0.49440542]
 [-0.03003345 -0.00601534]
 [ 0.531287   -0.3779337 ]
 ...
 [ 0.36814916 -0.4443905 ]
 [ 0.28471193 -0.43030402]
 [-0.02311547 -0.01046609]]
Layer: output_relu
